export default {
  ADDRESS: "Address",
  ADHAAR_NO: "Adhaar No",
  ALL: "All",
  BUYER: "Buyer",
  FLOWERS: "Flowers",
  FRUITS: "Fruits",
  GET_OTP: "Get OTP",
  GST_NO: "GST No",
  HOME: "Home",
  LOGIN: "Login",
  LOGOUT: "Logout",
  LOOKING_SELL: "Looking to Sell",
  LOOKING_BUY: "Looking to Buy",
  MOBILE_NO: "Mobile no",
  MY_MARKET: "myMarket",
  NAME: "Name",
  NEW_HERE: "New here?",
  PAN_NO: "PAN No",
  PASSWORD: "Password",
  PINCODE: "Pincode",
  REGISTER: "Register",
  REGISTERATION_TITLE_BUYER: "Buyer Registration",
  REGISTERATION_TITLE_SELLER: "Seller Registration",
  SELLER: "Seller",
  SIGNUP: "Sign Up",
  SUBMIT: "Submit",
  SUPPLY_TYPE: "Supply Type",
  USERNAME: "Username",
  VEGETABLES: "Vegetables",
};
